// * generated from firebase console
export const clientConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
};

// * generated by ./serviceAccount.json from firebase console
export const serverServiceAccountConfig = {
  type: process.env.FIREBASE_SERVER_TYPE,
  project_id: process.env.FIREBASE_SERVER_PROJECT_ID,
  private_key_id: process.env.FIREBASE_SERVER_PRIVATE_KEY_ID,
  private_key: process.env.FIREBASE_SERVER_PRIVATE_KEY,
  client_email: process.env.FIREBASE_SERVER_CLIENT_EMAIL,
  client_id: process.env.FIREBASE_SERVER_CLIENT_ID,
  auth_uri: process.env.FIREBASE_SERVER_AUTH_URI,
  token_uri: process.env.FIREBASE_SERVER_TOKEN_URI,
  auth_provider_x509_cert_url:
    process.env.FIREBASE_SERVER_AUTH_PROVIDER_X509_CERT_URL,
  client_x509_cert_url: process.env.FIREBASE_SERVER_CLIENT_X509_CERT_URL,
  universe_domain: process.env.FIREBASE_SERVER_UNIVERSE_DOMAIN,
};
